# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qk6VH-Kp_ugGTtV09W-UctBP3km2Yggj
"""

!pip -q install pandas numpy scikit-learn==1.6.1 joblib streamlit

# ==========================================
# CELL 1 — KINETICGRID SETUP
# ==========================================

import os
import sys
import gzip
import shutil
import hashlib
import warnings

import numpy as np
import pandas as pd
import joblib
import sklearn
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

print("==========================================")
print("⚡ KINETICGRID")
print("==========================================")

print("Python:", sys.version.split()[0])
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("Scikit-learn:", sklearn.__version__)
print("Joblib:", joblib.__version__)

print("\n✅ Libraries loaded.")

# ==========================================
# CELL 2 — VERIFY KINETICGRID FILES
# ==========================================

model_path = "/content/location_model.pkl"
encoder_path = "/content/location_encoder.pkl"
locations_path = "/content/locations.csv"

print("==========================================")
print("KINETICGRID FILE CHECK")
print("==========================================")

for path in [
    model_path,
    encoder_path,
    locations_path
]:
    print(
        f"{os.path.basename(path):30} → "
        f"{'✅ FOUND' if os.path.exists(path) else '❌ MISSING'}"
    )

# ==========================================
# CELL 3 — MODEL SIZE CHECK
# ==========================================

if not os.path.exists(model_path):
    raise FileNotFoundError(
        "location_model.pkl was not found in /content"
    )

model_size_bytes = os.path.getsize(model_path)

print("==========================================")
print("MODEL SIZE")
print("==========================================")

print(f"Bytes : {model_size_bytes:,}")
print(f"MB    : {model_size_bytes / (1024**2):,.2f}")
print(f"GB    : {model_size_bytes / (1024**3):,.3f}")

if model_size_bytes < 2 * 1024**3:
    print("\n⚠️ WARNING: This does not look like the original ~3 GB model.")
else:
    print("\n✅ This looks like the original large model.")

# ==========================================
# CELL 4 — MODEL FILE HEADER
# ==========================================

with open(model_path, "rb") as f:
    header = f.read(32)

print("First 32 bytes:")
print(header)

print("\nHex:")
print(header.hex())

print("\n✅ File header read successfully.")

# ==========================================
# CELL 5 — LOAD ORIGINAL MODEL
# ==========================================

print("⏳ Loading ORIGINAL location_model.pkl...")
print("Please wait. The model is approximately 3 GB.")

location_model = joblib.load(
    model_path
)

print("\n==========================================")
print("✅ ORIGINAL MODEL LOADED")
print("==========================================")

print("Model type:")
print(type(location_model))

# ==========================================
# EMERGENCY MODEL FILE CHECK
# ==========================================

import os

path = "/content/location_model.pkl"

size = os.path.getsize(path)

print("==========================================")
print("LOCATION MODEL CHECK")
print("==========================================")

print(f"Path: {path}")
print(f"Bytes: {size:,}")
print(f"MB: {size / (1024**2):,.2f}")
print(f"GB: {size / (1024**3):.3f}")

print("\nFile exists:", os.path.exists(path))

with open(path, "rb") as f:
    beginning = f.read(32)

print("\nFirst 32 bytes:")
print(beginning)

print("\nHex:")
print(beginning.hex())

import os

print("Possible model files:")
print("=" * 60)

for name in os.listdir("/content"):

    if "model" in name.lower():

        path = os.path.join("/content", name)

        if os.path.isfile(path):

            size = os.path.getsize(path)

            print(
                f"{name:40} "
                f"{size / (1024**2):,.2f} MB"
            )

import os

path = "/content/location_model.pkl"

if os.path.exists(path):
    os.remove(path)

print("✅ Empty location_model.pkl removed.")

print(os.path.exists("/content/location_model.pkl"))

import os

print("Files currently in /content:")
print("=" * 60)

for name in os.listdir("/content"):

    path = os.path.join("/content", name)

    if os.path.isfile(path):

        size = os.path.getsize(path)

        print(
            f"{name:45} "
            f"{size / (1024**2):,.2f} MB"
        )

from google.colab import files

print("Select the REAL location_model.pkl (~3 GB) from your computer.")
print("Do NOT select the old 453 MB compressed file.")

uploaded = files.upload()

print("\nUpload finished.")
for name in uploaded:
    print("Uploaded:", name)

from google.colab import drive

drive.mount("/content/drive")

import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for name in files:
        if name == "location_model.pkl":
            path = os.path.join(root, name)
            size = os.path.getsize(path)

            print("FOUND:")
            print(path)
            print(f"Size: {size:,} bytes")
            print(f"GB: {size / (1024**3):.3f}")

import os

print("Searching Google Drive for location_model.pkl...")
print("=" * 60)

found = []

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for name in files:
        if name == "location_model.pkl":
            path = os.path.join(root, name)
            size = os.path.getsize(path)

            found.append((path, size))

            print("FOUND:")
            print(path)
            print(
                f"Size: {size:,} bytes "
                f"({size / (1024**3):.3f} GB)"
            )
            print()

model_path = "/content/drive/MyDrive/location_model.pkl"

print("⏳ Loading ORIGINAL 3 GB model...")
location_model = joblib.load(model_path)

print("✅ MODEL LOADED!")
print(type(location_model))

location_model = joblib.load(model_path)

import os

print("Checking current Colab files:")
print("=" * 50)

for path in [
    "/content/location_encoder.pkl",
    "/content/locations.csv"
]:
    print(
        path,
        "→",
        "✅ FOUND" if os.path.exists(path) else "❌ NOT FOUND"
    )

encoder_path = "/content/location_encoder.pkl"
locations_path = "/content/locations.csv"

location_encoder = joblib.load(encoder_path)
locations = pd.read_csv(locations_path)

print("✅ Encoder loaded:", type(location_encoder))
print("✅ Locations loaded:", locations.shape)

model_path = "/content/drive/MyDrive/KineticGrid/location_model.pkl"

# ==========================================
# KINETICGRID — TEST PREDICTION
# ==========================================

print("Preparing test prediction...")

# Pick the first available location
test_location = (
    locations["Sensor_Name"]
    .dropna()
    .astype(str)
    .iloc[0]
)

test_row = locations[
    locations["Sensor_Name"].astype(str)
    == test_location
].iloc[0]

print("Test location:", test_location)

# Get sensor ID/code
if "Sensor_ID" in test_row.index:
    sensor_id = test_row["Sensor_ID"]
elif "Sensor_Code" in test_row.index:
    sensor_id = test_row["Sensor_Code"]
else:
    raise ValueError(
        "locations.csv has neither Sensor_ID nor Sensor_Code."
    )

# Encode
sensor_code = location_encoder.transform(
    [str(sensor_id)]
)[0]

# Same feature structure used by KineticGrid
test_input = pd.DataFrame({
    "Sensor_Code": [sensor_code],
    "Hour": [17],
    "DayOfWeek": [4],
    "MonthNum": [8],
    "DayOfMonth": [1],
    "IsWeekend": [0]
})

print("\nModel input:")
display(test_input)

# Predict
prediction = location_model.predict(
    test_input
)[0]

prediction = max(0, float(prediction))

print("\n==========================================")
print("⚡ KINETICGRID TEST RESULT")
print("==========================================")

print("Location:", test_location)
print(
    f"Predicted pedestrian count: "
    f"{prediction:,.0f}"
)

print("\n🎉 ORIGINAL MODEL + ENCODER + DATASET WORK!")

# ==========================================
# KINETICGRID — COMPRESS REAL MODEL
# ==========================================

import gzip
import shutil
import os

model_path = "/content/drive/MyDrive/location_model.pkl"

compressed_path = (
    "/content/drive/MyDrive/"
    "location_model.pkl.gz"
)

print("==========================================")
print("⚡ KINETICGRID MODEL COMPRESSION")
print("==========================================")

original_size = os.path.getsize(model_path)

print(
    f"Original size: "
    f"{original_size / (1024**3):.3f} GB"
)

print(
    f"Original bytes: "
    f"{original_size:,}"
)

print("\n⏳ Compressing...")
print("This may take a while.")
print("DO NOT interrupt Colab.")

with open(model_path, "rb") as f_in:

    with gzip.open(
        compressed_path,
        "wb",
        compresslevel=9
    ) as f_out:

        shutil.copyfileobj(
            f_in,
            f_out,
            length=16 * 1024 * 1024
        )

compressed_size = os.path.getsize(
    compressed_path
)

print("\n==========================================")
print("✅ COMPRESSION COMPLETE")
print("==========================================")

print(
    f"Compressed size: "
    f"{compressed_size / (1024**2):,.2f} MB"
)

print(
    f"Compressed bytes: "
    f"{compressed_size:,}"
)

print(
    f"Compression ratio: "
    f"{original_size / compressed_size:.2f}x"
)

print(
    "\nCompressed file:"
)

print(compressed_path)

# ==========================================
# KINETICGRID — VERIFY COMPRESSED MODEL
# ==========================================

import os
import gzip
import shutil

compressed_path = (
    "/content/drive/MyDrive/"
    "location_model.pkl.gz"
)

verification_path = (
    "/content/drive/MyDrive/"
    "location_model_verification.pkl"
)

original_path = (
    "/content/drive/MyDrive/"
    "location_model.pkl"
)

print("==========================================")
print("⚡ VERIFYING COMPRESSED MODEL")
print("==========================================")

original_size = os.path.getsize(
    original_path
)

compressed_size = os.path.getsize(
    compressed_path
)

print(
    f"Original:   {original_size / (1024**3):.3f} GB"
)

print(
    f"Compressed: {compressed_size / (1024**2):.2f} MB"
)

print("\n⏳ Decompressing for verification...")
print("This may take a few minutes.")

with gzip.open(
    compressed_path,
    "rb"
) as f_in:

    with open(
        verification_path,
        "wb"
    ) as f_out:

        shutil.copyfileobj(
            f_in,
            f_out,
            length=16 * 1024 * 1024
        )

verified_size = os.path.getsize(
    verification_path
)

print("\n==========================================")
print("VERIFICATION RESULT")
print("==========================================")

print(
    f"Original bytes:   {original_size:,}"
)

print(
    f"Recovered bytes:  {verified_size:,}"
)

print(
    f"Difference:       "
    f"{original_size - verified_size:,}"
)

if original_size == verified_size:

    print(
        "\n🎉🎉🎉 PERFECT!"
    )

    print(
        "The compressed model decompresses completely."
    )

else:

    print(
        "\n❌ SIZE MISMATCH!"
    )

    raise RuntimeError(
        "Compressed model is incomplete/corrupted."
    )

print("⏳ Loading verified decompressed model...")

verified_model = joblib.load(
    verification_path
)

print("\n✅ VERIFIED MODEL LOADED!")
print(type(verified_model))

original_prediction = location_model.predict(
    test_input
)[0]

verified_prediction = verified_model.predict(
    test_input
)[0]

print("\n==========================================")
print("⚡ PREDICTION COMPARISON")
print("==========================================")

print(
    "Original model:",
    original_prediction
)

print(
    "Compressed → decompressed:",
    verified_prediction
)

print(
    "Difference:",
    abs(
        original_prediction
        - verified_prediction
    )
)

if abs(
    original_prediction
    - verified_prediction
) < 1e-9:

    print(
        "\n🔥🔥🔥 100% VERIFIED!"
    )

    print(
        "Original and compressed models produce "
        "the same prediction."
    )

else:

    print(
        "\n⚠️ Prediction differs."
    )

# ============================================================
# ⚡ KINETICGRID — STREAMLIT APP
# ============================================================

import os
import gzip
import shutil
import tempfile

import joblib
import pandas as pd
import streamlit as st


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="KineticGrid",
    page_icon="⚡",
    layout="wide"
)


# ============================================================
# FILE PATHS
# ============================================================

MODEL_GZ = "location_model.pkl.gz"
ENCODER_PATH = "location_encoder.pkl"
LOCATIONS_PATH = "locations.csv"


# ============================================================
# HEADER
# ============================================================

st.title("⚡ KineticGrid")

st.markdown(
    """
    ## AI-Powered Pedestrian Activity Prediction

    KineticGrid uses a machine-learning model to predict
    pedestrian activity at selected locations.

    The prediction can then be used to estimate the potential
    kinetic energy available from pedestrian movement.
    """
)


# ============================================================
# CHECK REQUIRED FILES
# ============================================================

required_files = [
    MODEL_GZ,
    ENCODER_PATH,
    LOCATIONS_PATH
]

missing_files = [
    file for file in required_files
    if not os.path.exists(file)
]

if missing_files:

    st.error("❌ Required KineticGrid files are missing:")

    for file in missing_files:
        st.write(f"- `{file}`")

    st.stop()


# ============================================================
# LOAD LOCATIONS DATASET
# ============================================================

@st.cache_data
def load_locations():

    return pd.read_csv(
        LOCATIONS_PATH
    )


try:

    locations = load_locations()

except Exception as e:

    st.error("❌ Could not load locations.csv")
    st.exception(e)
    st.stop()


# ============================================================
# LOAD LOCATION ENCODER
# ============================================================

@st.cache_resource
def load_encoder():

    return joblib.load(
        ENCODER_PATH
    )


try:

    location_encoder = load_encoder()

except Exception as e:

    st.error(
        "❌ Could not load location_encoder.pkl"
    )

    st.exception(e)

    st.stop()


# ============================================================
# LOAD COMPRESSED MODEL
# ============================================================

@st.cache_resource
def load_model():

    # Temporary location for decompressed model
    temp_directory = tempfile.gettempdir()

    extracted_model = os.path.join(
        temp_directory,
        "kineticgrid_location_model.pkl"
    )

    # --------------------------------------------------------
    # Decompress only if it doesn't already exist
    # --------------------------------------------------------

    if not os.path.exists(
        extracted_model
    ):

        with gzip.open(
            MODEL_GZ,
            "rb"
        ) as compressed_file:

            with open(
                extracted_model,
                "wb"
            ) as model_file:

                shutil.copyfileobj(
                    compressed_file,
                    model_file,
                    length=16 * 1024 * 1024
                )

    # --------------------------------------------------------
    # Load decompressed model
    # --------------------------------------------------------

    return joblib.load(
        extracted_model
    )


try:

    with st.spinner(
        "⏳ Loading KineticGrid AI model..."
    ):

        location_model = load_model()

except Exception as e:

    st.error(
        "❌ Could not load the compressed model."
    )

    st.exception(e)

    st.stop()


# ============================================================
# MODEL READY
# ============================================================

st.success(
    "✅ KineticGrid AI model loaded successfully!"
)


# ============================================================
# VERIFY REQUIRED DATASET COLUMN
# ============================================================

if "Sensor_Name" not in locations.columns:

    st.error(
        "❌ `Sensor_Name` column was not found "
        "in locations.csv."
    )

    st.stop()


# ============================================================
# LOCATION LIST
# ============================================================

location_names = sorted(
    locations["Sensor_Name"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.header(
    "⚙️ Prediction Settings"
)

st.sidebar.markdown(
    "Choose the conditions for the prediction."
)


selected_location = st.sidebar.selectbox(
    "📍 Location",
    location_names
)


hour = st.sidebar.slider(
    "🕐 Hour",
    min_value=0,
    max_value=23,
    value=17
)


day_of_week = st.sidebar.slider(
    "📅 Day of Week",
    min_value=0,
    max_value=6,
    value=4,
    help="0 = Monday, 6 = Sunday"
)


month_num = st.sidebar.slider(
    "📆 Month",
    min_value=1,
    max_value=12,
    value=8
)


day_of_month = st.sidebar.slider(
    "📅 Day of Month",
    min_value=1,
    max_value=31,
    value=1
)


is_weekend = int(
    day_of_week >= 5
)


# ============================================================
# FIND SELECTED LOCATION
# ============================================================

selected_rows = locations[
    locations["Sensor_Name"].astype(str)
    == selected_location
]


if selected_rows.empty:

    st.error(
        "❌ Selected location was not found "
        "in locations.csv."
    )

    st.stop()


selected_row = selected_rows.iloc[0]


# ============================================================
# GET SENSOR ID
# ============================================================

if "Sensor_ID" in selected_row.index:

    sensor_id = selected_row["Sensor_ID"]

elif "Sensor_Code" in selected_row.index:

    sensor_id = selected_row["Sensor_Code"]

else:

    st.error(
        "❌ locations.csv contains neither "
        "`Sensor_ID` nor `Sensor_Code`."
    )

    st.stop()


# ============================================================
# ENCODE SENSOR
# ============================================================

try:

    sensor_code = location_encoder.transform(
        [str(sensor_id)]
    )[0]

except Exception as e:

    st.error(
        "❌ Unable to encode the selected location."
    )

    st.exception(e)

    st.stop()


# ============================================================
# CREATE MODEL INPUT
# ============================================================

model_input = pd.DataFrame({

    "Sensor_Code": [sensor_code],

    "Hour": [hour],

    "DayOfWeek": [day_of_week],

    "MonthNum": [month_num],

    "DayOfMonth": [day_of_month],

    "IsWeekend": [is_weekend]

})


# ============================================================
# MAIN INFORMATION
# ============================================================

st.subheader("📊 Prediction Configuration")

col1, col2, col3, col4 = st.columns(4)

with col1:

    st.metric(
        "📍 Location",
        selected_location
    )

with col2:

    st.metric(
        "🕐 Hour",
        f"{hour}:00"
    )

with col3:

    st.metric(
        "📅 Month",
        month_num
    )

with col4:

    st.metric(
        "Weekend",
        "Yes" if is_weekend else "No"
    )


# ============================================================
# PREDICTION BUTTON
# ============================================================

st.divider()

predict_button = st.button(
    "⚡ Predict Pedestrian Activity",
    type="primary",
    use_container_width=True
)


if predict_button:

    try:

        # ----------------------------------------------------
        # MODEL PREDICTION
        # ----------------------------------------------------

        prediction = location_model.predict(
            model_input
        )[0]

        prediction = max(
            0.0,
            float(prediction)
        )


        # ----------------------------------------------------
        # DISPLAY PREDICTION
        # ----------------------------------------------------

        st.subheader(
            "🚶 Predicted Pedestrian Activity"
        )

        result_col1, result_col2 = st.columns(2)

        with result_col1:

            st.metric(
                "Predicted Pedestrians / Hour",
                f"{prediction:,.0f}"
            )

        with result_col2:

            st.metric(
                "Predicted Pedestrians / Day",
                f"{prediction * 24:,.0f}"
            )


        # ----------------------------------------------------
        # KINETIC ENERGY ESTIMATION
        # ----------------------------------------------------

        st.divider()

        st.subheader(
            "⚡ Kinetic Energy Potential"
        )

        st.info(
            """
            The following is a prototype energy estimate
            based on the KineticGrid simulation assumptions.
            """
        )


        # ----------------------------------------------------
        # ENERGY ASSUMPTIONS
        # ----------------------------------------------------

        ENERGY_PER_STEP_MJ = 5.0

        SYSTEM_EFFICIENCY = 0.60


        # ----------------------------------------------------
        # CALCULATIONS
        # ----------------------------------------------------

        theoretical_energy_mj = (
            prediction
            * ENERGY_PER_STEP_MJ
        )

        usable_energy_mj = (
            theoretical_energy_mj
            * SYSTEM_EFFICIENCY
        )

        usable_energy_wh = (
            usable_energy_mj
            / 3600
        )


        energy_col1, energy_col2, energy_col3 = (
            st.columns(3)
        )


        with energy_col1:

            st.metric(
                "Energy / Pedestrian",
                "5 mJ"
            )


        with energy_col2:

            st.metric(
                "Theoretical Energy",
                f"{theoretical_energy_mj:,.2f} mJ"
            )


        with energy_col3:

            st.metric(
                "Usable Energy",
                f"{usable_energy_wh:,.4f} Wh"
            )


        # ----------------------------------------------------
        # MODEL INPUT DETAILS
        # ----------------------------------------------------

        st.divider()

        with st.expander(
            "🔎 View model input"
        ):

            st.dataframe(
                model_input,
                use_container_width=True
            )


        # ----------------------------------------------------
        # LOCATION INFORMATION
        # ----------------------------------------------------

        with st.expander(
            "📍 View selected location data"
        ):

            st.dataframe(
                selected_row.to_frame().T,
                use_container_width=True
            )


    except Exception as e:

        st.error(
            "❌ Prediction failed."
        )

        st.exception(e)


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "⚡ KineticGrid | AI-powered pedestrian activity "
    "and kinetic-energy harvesting simulation"
)

import os

compressed_path = "/content/drive/MyDrive/location_model.pkl.gz"

size = os.path.getsize(compressed_path)

print(f"Compressed model: {size:,} bytes")
print(f"MB: {size / (1024**2):,.2f} MB")
print(f"GB: {size / (1024**3):.3f} GB")